package br.unicamp.iel.model;
// Generated Aug 4, 2014 9:49:14 PM by Hibernate Tools 3.2.2.GA



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Long id;
     private String title;
     private String idiom;
     private String description;

    public Course() {
    }

	
    public Course(String title, String idiom) {
        this.title = title;
        this.idiom = idiom;
    }
    public Course(String title, String idiom, String description) {
       this.title = title;
       this.idiom = idiom;
       this.description = description;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getIdiom() {
        return this.idiom;
    }
    
    public void setIdiom(String idiom) {
        this.idiom = idiom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


