package br.unicamp.iel.model;
// Generated Jul 21, 2014 10:14:51 AM by Hibernate Tools 3.2.2.GA



/**
 * FunctionalWord generated by hbm2java
 */
public class FunctionalWord  implements java.io.Serializable {


     private Long id;
     private Course course;
     private String word;
     private String meaning;

    public FunctionalWord() {
    }

	
    public FunctionalWord(Course course) {
        this.course = course;
    }
    public FunctionalWord(Course course, String word, String meaning) {
       this.course = course;
       this.word = word;
       this.meaning = meaning;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getWord() {
        return this.word;
    }
    
    public void setWord(String word) {
        this.word = word;
    }
    public String getMeaning() {
        return this.meaning;
    }
    
    public void setMeaning(String meaning) {
        this.meaning = meaning;
    }




}


