package br.unicamp.iel.model;
// Generated Jul 25, 2014 3:29:38 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Justification generated by hbm2java
 */
public class Justification  implements java.io.Serializable {


     private Long id;
     private Date sentDate;
     private Date evaluatedDate;
     private String explanation;
     private byte state;
     private String user;
     private Set<JustificationMessage> messages = new HashSet<JustificationMessage>(0);

    public Justification() {
    }

	
    public Justification(Date sentDate) {
        this.sentDate = sentDate;
    }
    public Justification(Date sentDate, Date evaluatedDate, String explanation, byte state, String user, Set<JustificationMessage> messages) {
       this.sentDate = sentDate;
       this.evaluatedDate = evaluatedDate;
       this.explanation = explanation;
       this.state = state;
       this.user = user;
       this.messages = messages;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getSentDate() {
        return this.sentDate;
    }
    
    public void setSentDate(Date sentDate) {
        this.sentDate = sentDate;
    }
    public Date getEvaluatedDate() {
        return this.evaluatedDate;
    }
    
    public void setEvaluatedDate(Date evaluatedDate) {
        this.evaluatedDate = evaluatedDate;
    }
    public String getExplanation() {
        return this.explanation;
    }
    
    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }
    public byte getState() {
        return this.state;
    }
    
    public void setState(byte state) {
        this.state = state;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Set<JustificationMessage> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<JustificationMessage> messages) {
        this.messages = messages;
    }




}


