package br.unicamp.iel.model;
// Generated Jul 29, 2014 3:21:28 PM by Hibernate Tools 3.2.2.GA



/**
 * Module generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private Long id;
     private Course course;
     private Integer position;
     private String grammar;

    public Module() {
    }

	
    public Module(Course course) {
        this.course = course;
    }
    public Module(Course course, Integer position, String grammar) {
       this.course = course;
       this.position = position;
       this.grammar = grammar;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }
    public String getGrammar() {
        return this.grammar;
    }
    
    public void setGrammar(String grammar) {
        this.grammar = grammar;
    }




}


