package br.unicamp.iel.model;
// Generated Aug 29, 2014 11:33:34 PM by Hibernate Tools 3.2.2.GA



/**
 * ReadInWebAnswer generated by hbm2java
 */
public class ReadInWebAnswer  implements java.io.Serializable {


     private Long id;
     private String user;
     private String answer;
     private Question question;

    public ReadInWebAnswer() {
    }

	
    public ReadInWebAnswer(Question question) {
        this.question = question;
    }
    public ReadInWebAnswer(String user, String answer, Question question) {
       this.user = user;
       this.answer = answer;
       this.question = question;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }




}


