package br.unicamp.iel.model;
// Generated Aug 26, 2014 12:31:43 PM by Hibernate Tools 3.2.2.GA



/**
 * ReadInWebControl generated by hbm2java
 */
public class ReadInWebControl  implements java.io.Serializable {


     private Long id;
     private Activity activity;
     private String user;
     private Integer control;

    public ReadInWebControl() {
    }

	
    public ReadInWebControl(Activity activity, Integer control) {
        this.activity = activity;
        this.control = control;
    }
    public ReadInWebControl(Activity activity, String user, Integer control) {
       this.activity = activity;
       this.user = user;
       this.control = control;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Activity getActivity() {
        return this.activity;
    }
    
    public void setActivity(Activity activity) {
        this.activity = activity;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Integer getControl() {
        return this.control;
    }
    
    public void setControl(Integer control) {
        this.control = control;
    }




}


