package br.unicamp.iel.model;
// Generated Feb 6, 2015 10:24:22 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Strategy generated by hbm2java
 */
public class Strategy  implements java.io.Serializable {


     private Long id;
     private Integer position;
     private Integer type;
     private Activity activity;
     private String body;
     private Date modified;

    public Strategy() {
    }

	
    public Strategy(Activity activity) {
        this.activity = activity;
    }
    public Strategy(Integer position, Integer type, Activity activity, String body, Date modified) {
       this.position = position;
       this.type = type;
       this.activity = activity;
       this.body = body;
       this.modified = modified;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Activity getActivity() {
        return this.activity;
    }
    
    public void setActivity(Activity activity) {
        this.activity = activity;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }




}


